### ISSUE TITLE
Card under Violence against Children and Women

### ISSUE THREAD

**Issue by lbassil** [UNICEFECAR/dash#18]
Why is this card showing a value of 0? And why are we dividing by a population knowing that the indicator itself is a percentage:

{
                "name": "who experienced physical punishment or psychological aggression by caregivers",
                "indicator": "PT_CHLD_1-14_PS-PSY-V_CGVR",
                "denominator": "EDUNF_SAP_L1T3",
                "suffix": "Percent of Children",
            },
I exported the data from the SDMX and filtered by Total for Age and Residence and Sex and got the below... is Wealth also taken into consideration in this case?
![image](https://user-images.githubusercontent.com/86417315/125859623-f7546494-69c8-4194-a1fd-d51232ae6ec3.png)

**Comment by beto-Sibileau** [comment]
hi @lbassil, thanks for bringing this one, I will check what's happening there it could be zero returning because country and year should match between numerator and denominator for the card to be computed. The thing is that averages can't be averaged across the region, you need first to turn an average into a number and then do the average.

**Comment by beto-Sibileau** [comment]
card debugged: code worked properly, this is an issue about the quality of data --> basically we can't bring in any indicator into cards nor area_2 in the dashboard that has disaggregation + total codes in their disaggregated dimensions but none data points that correspond to all totals, because we can't display any data for cards nor timeline (only available area for display would be area_1)
