### ISSUE TITLE
Revise card: Children in Residential Care Rate

### ISSUE THREAD

**Issue by beto-Sibileau** [UNICEFECAR/dash#9]
![image](https://user-images.githubusercontent.com/62593695/122249780-6b5df480-cec9-11eb-8882-2118dcc06137.png)

1) check absolute flag in Cards Config
2) if not 1. --> debug

**Comment by beto-Sibileau** [comment]
@lbassil thanks for raising this one !!! I have checked it and it is OK, the problem with this one is that the **UNIT_MEASURE** is rate per hundred thousand population, therefore the algorithm is correct but what we need to correct is the label and change PERCENT of children to Children per 100,000 population !!!
Could you please take care of that config change please and close this issue when done? Many thanks!

**Comment by lbassil** [comment]
Hi @beto-Sibileau , following the new structure of the Child Protection page, this indicator is no more added as a card. Please confirm so this issue is closed.
However, under violence, they selected this indicator: PT_CHLD_1-14_PS-PSY-V_CGVR that we agreed it cannot be added as a card. Please also confirm the same to ask for a change.

**Comment by beto-Sibileau** [comment]
@lbassil sure Layale, well noted both, I can't access now the documentation about cards revision and I trust you double checked, thank you !!!
- Rate of children in residential care has been taken out of the cards according to last revision
- PT_CHLD_1-14_PS-PSY-V_CGVR: can't be used since there's no **TOTAL** on all 4 dimensions: *sex, age, residence and wealth*
